<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle(' ' . $this->translate('My insta'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/myinsta.css'))
        ->prependStylesheet($this->basePath('css/croppic.css'))
        ->prependStylesheet($this->basePath('css/sidebar.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

    <!-- Scripts -->
    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="http://jqueryvalidation.org/files/dist/jquery.validate.min.js"></script>
    <script src="http://jqueryvalidation.org/files/dist/additional-methods.min.js"></script>
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/myjs.js'))
        ->prependFile($this->basePath('js/whammy.js'))
        ->prependFile($this->basePath('js/jsHtml5VideoRecorder.js'))
        ->prependFile($this->basePath('js/croppic.js'))
        ->prependFile($this->basePath('js/croppic.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',)); ?>

</head>
<body>
<nav class="navbar navbar-fixed-top nav-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                <img src="<?php echo $this->basePath('img/myinst.png') ?>" style="width: 30px; height: 20px;"
                     alt="My insta"/>
                &nbsp;<?php echo $this->translate('My insta') ?></a>
        </div>
        <?php
        if (isset($_SESSION['user'])) {
        ?>
        <div class="search">

            <div class="resultSearch">
                <ul class="nav nav-pills">
                    <li class="dropdown">
                        <form method="post" action="<?php $this->url('default',array('controller' => 'user', 'action' => 'search'));?>"
                              class=" navbar-search">
                            <input type="text" class="form-control search-query" placeholder="Search..." name="search" id="search">
                        </form>
                        <ul class="dropdown-menu dropdown-list">
                        </ul>
                    </li>
                </ul>

            </div>
        </div>
        <?php } ?>
        <div class="collapse navbar-collapse pull-right">
            <?php
            if (!isset($_SESSION['user'])) {
                ?>

                <form class="form-inline" role="form" method="post">
                    <div class="form-group">
                        <input type="email" class="form-control layout-form" placeholder="Enter email"
                               name="emailLogin">
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control layout-form" placeholder="Password" name="passLogin">
                    </div>
                    <button type="submit" class="btn btn-default" name="submitlog">LOG IN</button>
                </form>
            <?php } else { ?>
                <div class="authUser">
                    <a href="<?php echo $this->url('default', array('controller' => 'user', 'action' => 'index')) ?>">
                        <?= "Hello " . $_SESSION['user'];  ?></a>
                    <button type="button" class="btn btn-default"><a href="<?= $this->url('default',
                            array('controller'=>'user', 'action' => 'logout'));?>">Log out</a></button>
                </div>

            <?php } ?>
        </div>
        <!--/.nav-collapse -->
    </div>
</nav>
<div class="content">
    <?php echo $this->content; ?>
    <hr>

</div>

<!-- /container -->
<footer>
    <div class="col-md-6 col-md-offset-3">
        <nav class="navbar navbar-default nav-footer">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="#">MyInsta</a>
                <a class="navbar-brand" href="#">About</a>
                <a class="navbar-brand" href="#">Support</a>
                <a class="navbar-brand" href="#">Contact us</a>
            </div>
        </nav>
    </div>
</footer>
<?php echo $this->inlineScript() ?>
</body>
</html>
