<?php
$form = $this->form;
$form->prepare(); // The correct enctype is set here
$user = $this->user;
$isFollow = $this->isFollow;
$inf = $this->inf;
?>
<div class="col-md-6 col-md-offset-3 profile">
    <div class="inf">
        <table>
            <tr>
                <td rowspan="3" class="ava"><img class="img-circle" style="width: 250px;height:250px;"
                                                 src="img/<?= $user->ava; ?>"/></td>
                <td><a id="userLink" href="#" name="<?= $user->link; ?>"><h3><?= $user->name; ?></h3></a></td>
            </tr>
            <tr>
                <td>
                    <div class="col-md-4">
                        <p><strong><?= $inf['postCount']; ?></strong> post</p>
                    </div>
                    <div class="col-md-4">
                        <p><strong><?= $inf['followersCount']; ?></strong> followers</p>
                    </div>
                    <div class="col-md-4">
                        <p><strong><?= $inf['followingCount']; ?></strong> following</p>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <?php if (isset($_SESSION['userEmail']) && $_SESSION['userEmail'] == $user->email) { ?>
                        <a class="btn btn-success" href="/user/edit">
                            Edit profile
                        </a>
                    <?php } else { ?>
                        <a class="btn btn-success follow" href="#" name="<?= $user->id ?>">
                            <?= $isFollow ? "Following" : "Follow" ?>
                        </a>
                    <?php } ?>
                </td>
            </tr>
        </table>
    </div>
    <?php if (isset($_SESSION['userEmail']) && $_SESSION['userEmail'] == $user->email) { ?>
        <div class="post">
            <?php echo $this->form()->openTag($form); ?>
            <div class="form-group">
                <textarea rows="3" cols="90" name="post" placeholder="What's new?"></textarea>
            </div>
            <div class="form-element">
                <?php $fileElement = $form->get('image-file'); ?>
                <?php echo $this->formFile($fileElement); ?>
                <?php echo $this->formElementErrors($fileElement); ?>
                <button type="submit" class="btn btn-primary send-post">Send</button>
            </div>

            <?php echo $this->form()->closeTag(); ?>

        </div>
    <?php } ?>
    <div class="myphoto">

        <?php $posts = $this->posts;
        foreach ($posts as $post) {
            $url = explode('/', $post->urlImg);
            ?>
            <div class="profile-img">
                <a><img src="img/<?php echo $url[7]; ?>" id="img_<?= $post->id_post; ?>"/></a>

                <div class="like-comment">
                    <img src="img/like.png"> <span>0</span>
                    <img src="img/comment.png"> <span>0</span>
                </div>
            </div>
        <?php } ?>


    </div>
    <?php if (!($posts->count() < 9)) { ?>
        <button type="button" class="btn btn-primary" id="loadMore">Load more</button>
    <?php } ?>
</div>

<div class="showImg">
    <span class="glyphicon glyphicon-remove close">assssssssssssХ</span>

    <div id="ImgWithComment" class="col-md-6 col-md-offset-3 row">
        <article>
            <section>
                <header></header>
                <div class="img-block"></div>
                <div class="comment-img">
<!--                    <input type="button" id="showMoreComment" value="view all comments" />-->
                    <div id="list-comment">
                    <ul id="comments">
                    </ul>
                    </div>
                    <section>
                        <form method="post" action="" class="comment-form">
                            <input id="comment-text" type="text" class="form-control" name="mycomment"
                                   placeholder="Add a comment...">
                        </form>
                        <a id="btn-send-comment" class="btn btn-success">Send</a>
                    </section>
                </div>
            </section>
        </article>
    </div>
</div>

