<div class="col-md-6 col-md-offset-3 profile">
    <div class="inf">
        <table>
            <tr>
                <td rowspan="3" class="ava"><img src="<?php echo $this->basePath('img/leo.jpg');?>" class="img-circle"/></td>
                <td><a href="#"><h3><?php echo $_SESSION['user']; ?></h3></a></td>
            </tr>
            <tr>
                <td>
                    <div class="col-md-4">
                        posts<span>0</span>
                    </div>
                    <div class="col-md-4">
                        followers<span>0</span>
                    </div>
                    <div class="col-md-4">
                        following<span>0</span>
                    </div>
                </td>
            </tr>
            <tr>
                <td></td>
            </tr>
        </table>
    </div>
    <div class="post">
        <form role="form">
            <div class="form-group">
                <textarea rows="3" cols="90" name="text" placeholder="What's new?"></textarea>
                <button><span class="glyphicon glyphicon-camera"></span></button>
            </div>
            <div class="form-group">
                <input type="file" id="InputFile">
            </div>
            <button type="submit" class="btn btn-primary">Send</button>
        </form>
    </div>s
    <div class="myphoto">
        <img src="<?php echo $this->basePath('img/leo.jpg'); ?>"/>
        <img src="<?php echo $this->basePath('img/leo.jpg'); ?>"/>
        <img src="<?php echo $this->basePath('img/leo.jpg'); ?>"/>
    </div>
</div>