<?php
$user = $this->user;
$isFollow = $this->isFollow;
$inf = $this->inf;
?>
<div class="col-md-6 col-md-offset-3 profile">
    <div class="inf">
        <table>
            <tr>
                <td rowspan="3" class="ava"><img class="img-circle" style="width: 250px;height:250px;"
                                                 src="img/<?= $user->ava; ?>"/></td>
                <td><a id="userLink" href="#" name="<?= $user->link; ?>"><h3><?= $user->name; ?></h3></a></td>
            </tr>
            <tr>
                <td>
                    <div class="col-md-4">
                        <p><strong><?= $inf['postCount']; ?></strong> post</p>
                    </div>
                    <div class="col-md-4">
                        <p><strong><?= $inf['followersCount']; ?></strong> followers</p>
                    </div>
                    <div class="col-md-4">
                        <p><strong><?= $inf['followingCount']; ?></strong> following</p>
                    </div>
                </td>
            </tr>

            <tr>
                <td>
                    <?php if (isset($_SESSION['userEmail']) && $_SESSION['userEmail'] == $user->email) { ?>
                        <a class="btn btn-success" href="/user/edit">
                            Edit profile
                        </a>
                    <?php } else { ?>
                        <a class="btn btn-success follow" href="#" name="<?= $user->id ?>">
                            <?= $isFollow ? "Following" : "Follow" ?>
                        </a>
                    <?php } ?>
                </td>
            </tr>
        </table>
    </div>
    <?php if (isset($_SESSION['userEmail']) && $_SESSION['userEmail'] == $user->email) { ?>

        <div class="post">
            <div class="form-group">
                <textarea rows="3" cols="90" name="post" placeholder="What's new?"></textarea>
            </div>

            <div class="form-element">
                <div id="cropContainerHeader"></div>
                <button type="submit" class="btn btn-primary send-post" id="btn-send-post">Send</button>
            </div>

        </div>
    <?php } ?>
    <div class="myphoto">
        <?php $posts = $this->posts;
        foreach ($posts as $post => $value) {

            ?>
            <div class="profile-img">
                <a><img class="profile-post" src="<?php echo $value['urlImg']; ?>" id="img_<?= $value['id_post']; ?>"/></a>

                <div class="like-comment">
                    <img class="profile-like" src="<?= ($value['isLike']) ? '/img/like.png' : '/img/unlike.png'?>">
                    <span><?= $value['countLike']; ?></span>
                    <img src="/img/comment.png">
                    <span><?= $value['countComment']; ?></span>
                </div>
            </div>
        <?php } ?>


    </div>
    <?php if (!(sizeof($posts) < 9)) { ?>
        <button type="button" class="btn btn-primary" id="loadMore">Load more</button>
    <?php } ?>
</div>

<div class="showImg">
    <span class="glyphicon glyphicon-remove close">assssssssssssХ</span>

    <div id="ImgWithComment" class="col-md-6 col-md-offset-3 row">
        <article>
            <section>
                <header>
                    <?php if (isset($_SESSION['userEmail']) && $_SESSION['userEmail'] == $user->email) { ?>
                    <button class="btn btn-info">Make ava</button>
                    <?php } ?>
                </header>
                <div class="img-block"></div>
                <div class="comment-img">
<!--                    <input type="button" id="showMoreComment" value="view all comments" />-->
                    <div id="list-comment">
                    <ul id="comments">
                    </ul>
                    </div>
                    <section>
                        <form method="post" action="" class="comment-form">
                            <input id="comment-text" type="text" class="form-control" name="mycomment"
                                   placeholder="Add a comment...">
                        </form>
                        <a id="btn-send-comment" class="btn btn-success">Send</a>
                    </section>
                </div>
            </section>
        </article>
    </div>
</div>
