<h1>NEWS</h1>
<div class="col-md-6 col-md-offset-3 news">
    <ul class="nav nav-tabs">
        <li class="active">
            <a href="?type=all-news">All</a>
        </li>
        <li><a href="?type=following-news" >Following</a></li>
        <li><a href="?type=my-news">My news</a></li>
    </ul>
    <div>
        <?php
        $news = $this->news;
        if ($news) {
            foreach ($news as $n) {
                ?>
                <div class="result ">
                    <article>
                        <header class="author-new">
                            <img src="/img/<?= $n['ava']; ?>" class="img-circle">
                            <a href="/user?id=<?= $n['idUser'] ?>"><strong><?= $n['name']; ?></strong></a>
                        </header>
                        <div class="new-post" data-post="<?= $n['id_post'];?>">
                            <img src="<?= $n['urlImg']; ?>">
                            <p>like <span><?= $n['countLike'] . " "; ?></span>Comment <span><?= $n['countComment']; ?></span></p>
                        </div>
                        <form class="form-inline" role="form">
                            <div class="like-icon">
                                <a class="btn-default">
                                    <img class="<?= ($n['isLike']) ? 'like' : ''; ?>"
                                         src="<?= ($n['isLike']) ? $this->basePath('/img/like.png') : $this->basePath('/img/unlike.png'); ?>">
                                </a>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Enter your comment">
                            </div>
                            <button type="submit" class="btn btn-default">SEND</button>
                        </form>
                    </article>
                </div>
            <?php }
        } ?>
    </div>
</div>
